### ISSUE TITLE
Needs an official maintainer

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/bootstrap_lite#18]
There's nothing in the README about who is maintaining this theme.

Originally it was @Gormartsen but I believe he's moved on to other things. He can confirm if he'd like anyone to take this over.

**Comment by stpaultim** [comment]
@yorkshire-pudding has expressed an interest in helping with this module and no one is listed as the official maintainer. I'm willing to put myself down as maintainer and possibly work with @yorkshire-pudding. 

Unless, @Gormartsen is still interested. Which is also fine with me. 

Since no one is officially listed as the maintainer, should we wait two weeks for this to take effect or do you think we could go ahead and make this official right away?

**Comment by yorkshire-pudding** [comment]
@stpaultim thanks

**Comment by stpaultim** [comment]
I've created a PR to add myself as maintainer. Would @jenlampton or @klonos be able to give me full permissions on this repo?

https://github.com/backdrop-contrib/bootstrap_lite/pull/22

**Comment by jenlampton** [comment]
gladly!

**Comment by stpaultim** [comment]
@bugfolder has agreed to become a co-maintainer on this theme.

**Comment by bugfolder** [comment]
Yup.

**Comment by stpaultim** [comment]
@bugfolder You have been added as a full admin of this project and the Readme file has been updated.
