### ISSUE TITLE
Update API URL

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/bootstrap_lite#19]
The Bootswatch page is basically empty, because the API URL it's trying to call is old and doesn't work anymore. The current API URL is: `https://bootswatch.com/api/4.json`

**Comment by cellear** [comment]
This issue is now RTBC - I've tested the pull request, and it works as advertised -- the list of Bootswatch themes showed up in Theme Settings, and selecting one seemed to update the colors.  Screenshot enclosed.

I noticed one problem: The fonts didn't seem to download.  However, that's not the problem identified in this issue, so I'll open up a new one.
![Bootswatch-in-bootstrap-lite-settings-top](https://user-images.githubusercontent.com/757296/102150638-eb75a580-3e25-11eb-9f6c-ae476fc80d55.jpg)

**Comment by yorkshire-pudding** [comment]
Any ideas when this will be in the release?  I only found this by looking for closed issues, but I wouldn't expect it to be closed until a release was ready, unless I'm misunderstanding.

Managed to fix by manually applying the edit.
