### ISSUE TITLE
Question about (lack of) responsiveness with image fields

### ISSUE THREAD

**Issue by ilfelice** [backdrop-contrib/bootstrap_lite#56]
Howdy,

I am testing Backdrop with the Bootstrap Lite theme as a replacement (upgrade) for an existing Drupal 7 that uses the D7 Bootstrap 3 theme.

Overall the content transition works fine, but I have noticed that the image fields are not responsive in Bootstrap Light (unless I am missing something).

For now I have added the following code to my sub-theme template.php:

```
function global_image($variables) {
  return '<img class="img-responsive"' . backdrop_attributes($variables['attributes']) . ' />';
}
```
The above works fine, but I was wondering if this is the correct solution to this issue.
(If it is, perhaps this can be added to the theme by default)

**Comment by bugfolder** [comment]
Hi @ilfelice, the Backdrop Bootstrap Lite theme isn't a plug-in replacement for the D7 Bootstrap theme; that's the "Lite" part of the name. So, while the D7 theme offers some image settings ("Default image shape" and "Responsive images" checkbox), that's not part of Bootstrap Lite.

Overriding the image rendering in a sub-theme, as you've done, is an appropriate way to add that class. (You could also do it with a template file, similarly to the way it's done in D7; or (I think) add the class to the `$variables['attributes']['class']` array, which is the method I'd incline toward.

As for adding it to the theme by default, we wouldn't want to just add this class automatically, because existing installations and sub-themes might not be expecting that class to be present. So it would need to be added via an optional setting whose default value is off, to preserve the existing behavior for all of the existing sites that use this theme. If you were inclined to try to add it, I'd suggest it would belong in the "Tweaks" vertical tab (where the Container type setting resides).

**Comment by ilfelice** [comment]
Hello bugfolder,

Thank you for the prompt response!

Now I understand the "Lite" aspect of the theme. Not being a coder, I am unable to code the feature myself; but since even in it's light form the theme has been very useful for the purpose that I am shooting for, I will stick to the current solution that I am using.

Thank you again for the detailed explanation!

PS: should I close this issue?

**Comment by bugfolder** [comment]
It's a good idea. Let's leave the issue open, and maybe I or my co-maintainer will add it. It would be nice to make the path of upgrading from D7 Bootstrap theme easier.

**Comment by ilfelice** [comment]
Howdy!

> It would be nice to make the path of upgrading from D7 Bootstrap theme easier.

Agreed! :)

**Comment by bugfolder** [comment]
Hi @ilfelice, I've created a PR that implements this. Care to try it out?

@stpaultim are you OK with adding this to the theme? It does bring it closer to parity with D7 Bootstrap theme. (You'll notice that I've started adding the vertical tab display JS for Tweaks; I plan to add it for the others, but maybe in a separate issue.)

**Comment by ilfelice** [comment]
Howdy!

Thank you for looking into this. I will try this PR, but I will need some time (life is busy).

Thank you for your patience!

**Comment by bugfolder** [comment]
Re-pinging @stpaultim: OK with adding this setting to the theme?
