### ISSUE TITLE
grid-flexbox is overriding the width set by Bootstrap Lite

### ISSUE THREAD

**Issue by vtad** [backdrop-contrib/bootstrap_lite#9]
Env: backdrop 1.4.2 , Bootstrap lite 1.x-1.3.5-beta1
I am using fixed width (1170px) in the theme tweak.

The max-width css definition for **.container** in 
http://ta-camp.de/core/modules/layout/css/grid-flexbox.css
constrains the with. See http://ta-camp.de/node/1537

This does not happen with the (old) flexbox layout. See http://ta-camp.de/

**Comment by Gormartsen** [comment]
Tnx @vtad !

I noticed it as well.

On my own side I had to do a hack :

```
.container .container {
Max-width: auto;

}
```

I need to rethink this theme structure.

There is possible more conflicts in a future.

**Comment by vtad** [comment]
which css file did you change?

**Comment by Gormartsen** [comment]
You can add it to overrides 

Regards,
Gor Martsen
@gormartsen

**Comment by lynna-spidersilk** [comment]
Trying to override it there, or in style.css, doesn't work for me, even with !important added. The flexbox CSS always overrides mine no matter where I put it. There appears to be no way to get the layout of a Bootstrap subtheme to display at the proper width. 

Is there any way around this? There doesn't appear to be any way to opt out of, or override, Backdrop's layout system, or to change the code that's constraining the width without hacking core. But it seems like there must be a way, because other themes aren't shrunk to such a narrow width... 

(Kind of starting to wish I'd just stuck with Drupal...)

**Comment by laryn** [comment]
@lynna-spidersilk This would be a good question for the forum or Gitter chat. I know there are other folks who have used Bootstrap.

https://forum.backdropcms.org

**Comment by lynna-spidersilk** [comment]
Ah - found an answer there! For anyone else who may be searching: https://forum.backdropcms.org/forum-topic/how-stop-loading-default-grid-flexboxcss

**Comment by stpaultim** [comment]
I am going to close this issue. Feel free to reopen if anyone has questions or would like to suggest improvements.

**Comment by stpaultim** [comment]
I pushed a temporary solution until I have time to figure out a better solution. Currently, I've added the following to the override.css file:

```
@media (min-width: 1200px) {
  .container {
    max-width: 1170px;
  }
}
```

**Comment by bugfolder** [comment]
Any further comments from anyone? Is this now ready to be closed?
